name: CI

on:
  push:
    branches: [ 'main', 'master' ]
  pull_request:
    branches: [ 'main', 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --no-audit --no-fund
      - name: Build
        run: pnpm -w -r run build --if-present
      - name: Lint
        run: pnpm -w -r run lint --if-present
      - name: Typecheck
        run: pnpm -w -r run typecheck --if-present
      - name: Test
        run: pnpm -w -r run test --if-present
